### ISSUE TITLE
Update to Laravel 5.5

### ISSUE THREAD

**Issue by rjsworking** [rinvex/laravel-cacheable#11]
Hi @Omranic 

Can you update this package? Thanks in advance.

Cheers

**Comment by Omranic** [comment]
@ruijsdev what's exactly needs an update?

**Comment by Omranic** [comment]
Ah, if you mean Laravel 5.5 support, it's already supported on the `develop` branch, check it out 😉

**Comment by rjsworking** [comment]
Sorry. I meant support for L5.5. 
Thank you very much :-)
