### ISSUE TITLE
data folder inside framework/cache/ not created after cache:clear

### ISSUE THREAD

**Issue by null9beta** [rinvex/laravel-cacheable#12]
Hi,

i have a question regarding writing the `rinvex.cacheable.json` file into the cache folder.

My Setup:
------------
I basically got the `rinvex/attributable` package loaded and the `rinvex/cacheable` is used through it.

Problem:
------------
Whenever you run `artisan cache:clear` and run anything afterwards like calling a controller that loads a model implementing the attributable behavior, creating the cache file fails.

````
file_put_contents(/Users/.../storage/framework/cache/data/rinvex.cacheable.json): failed to open stream: No such file or directory
```

The referring Code is in `cacheable/src/CacheableEloquent.php:99`
```
protected static function storeCacheKey(string $modelName, string $cacheKey)
    {
        $keysFile = storage_path('framework/cache/data/rinvex.cacheable.json');
        $cacheKeys = static::getCacheKeys($keysFile);
        if (! isset($cacheKeys[$modelName]) || ! in_array($cacheKey, $cacheKeys[$modelName])) {
            $cacheKeys[$modelName][] = $cacheKey;
            file_put_contents($keysFile, json_encode($cacheKeys));
        }
    }
```

Actually if the data folder inside framework/cache is not present creating the file will fail.
Manually creating the folder and everything is fine.

My Question
---------------
Shall i provide a PullRequest that simply checks if the folder exists and creates it?

Best
null9beta

**Comment by null9beta** [comment]
Hi,

as i just realized that the `getCacheKeys` method is supposed to create the folder/file if missing as well i provided a hotfix PR to fix the problem.

Best
null9beta

**Comment by Omranic** [comment]
Thank you, this is already fixed here https://github.com/rinvex/laravel-cacheable/blob/master/src/CacheableEloquent.php#L88-L92
