### ISSUE TITLE
Set cache driver and cache lifetime

### ISSUE THREAD

**Issue by rjsworking** [rinvex/laravel-cacheable#15]
Hi. Not really an issue but I'm not figuring out how to set cache driver and cache lifetime. 
The cache works ok with the default cache driver.

Thanks in advance

**Comment by Omranic** [comment]
Well, you can change caching behavior by adding the appropriate property to your model as follows:
```php
    /**
     * Indicate if the model cache clear is enabled.
     *
     * @var bool
     */
    protected static $cacheClearEnabled = true;

    /**
     * The model cache driver.
     *
     * @var string
     */
    protected $cacheDriver;

    /**
     * The model cache lifetime.
     *
     * @var float|int
     */
    protected $cacheLifetime = -1;
```

Through these properties, you can enable/disable caching, change cache driver, or change cache lifetime as well.

Reference: https://github.com/rinvex/cacheable/blob/master/src/CacheableEloquent.php#L26-L45

Please feel free to open this issue or a new one if you've any further questions 😉

**Comment by rjsworking** [comment]
Problem solved.

Thank you very much :+1: 

Cheers
