### ISSUE TITLE
getCacheLifetime return type error

### ISSUE THREAD

**Issue by wuwx** [rinvex/laravel-cacheable#16]
Type error: Return value of Rinvex\Attributes\Models\AttributeEntity::getCacheLifetime() must be of the type integer, null returned

because

```php
    public function getCacheLifetime(): int
    {
        return $this->cacheLifetime;
    }
```

```php
    public function resetCacheConfig()
    {
        $this->cacheDriver = null;
        $this->cacheLifetime = null;

        return $this;
    }
```

set cacheLifetime to null

**Comment by Omranic** [comment]
I was wondering why we get this behaviour since we already have default value, but finally fixed it correctly at 6eb5e903b532dacd1b5f647532cf9d967ec76f65 Check now please & let me know if there's any further issues..
