### ISSUE TITLE
Cannot install on LV5.5 and PHP 7.1

### ISSUE THREAD

**Issue by sarfraznawaz2005** [rinvex/laravel-cacheable#17]
I tried to install but got this error:

![image](https://user-images.githubusercontent.com/201788/35228455-977f6bbe-ffb2-11e7-8097-42bc3207c1c4.png)

**Comment by Omranic** [comment]
This package still not yet tagged as stable. You can only use **develop** branch for now, use: `composer require rinvex/cacheable:dev-develop` it should work smoothly even it's still in development. Please feel free to reopen this issue or a new issue, if you need further assistance :)

**Comment by sarfraznawaz2005** [comment]
thanks :)
