### ISSUE TITLE
Overriding $cacheLifetime

### ISSUE THREAD

**Issue by BrekiTomasson** [rinvex/laravel-cacheable#19]
Hi!

I'm using this trait in a model where the default lifetime of -1 doesn't make sense, so I'm trying to change it to another number by adding `protected $cacheLifetime = 10;` into my class definition. However, it keeps FatalErrorException:ing on me and spitting back: `App\Model\<myModel> and Rinvex\Cacheable\CacheableEloquent define the same property ($cacheLifetime) in the composition of App\Model\<myModel>.`.

Any suggestions?

**Comment by Omranic** [comment]
Fixed e14a3abb2ac4cf48efc62e839f0c04b9de6f79cf
