### ISSUE TITLE
Event::fire has been removed.

### ISSUE THREAD

**Issue by moecasts** [rinvex/laravel-cacheable#27]
PHP Error:  Call to undefined method Illuminate/Events/Dispatcher::fire() in /var/www/nya/vendor/rinvex/laravel-cacheable/src/CacheableEloquent.php on line 222

source: [https://github.com/rinvex/laravel-cacheable/blob/7112fc4375e39f7876fe82df1f0a4bde4702f90b/src/CacheableEloquent.php#L220-L222](url)

**Comment by dom235** [comment]
There has been an hot fix https://github.com/rinvex/laravel-cacheable/commit/7112fc4375e39f7876fe82df1f0a4bde4702f90b without an hot fix at all, just bumping the release ;- D

**Comment by Omranic** [comment]
@schranzer235 thanks for pointing that out, I hope you mentioned it earlier 🙂 
The fix was pushed only to `develop` three days ago, and been missed out from `master`.
Now it's fixed, for real! cbbb3863524a01646eb12f17ad78aa238eee0789
