### ISSUE TITLE
How to disable cache for RAND()

### ISSUE THREAD

**Issue by kimtrien** [rinvex/laravel-cacheable#31]
I have a query builder using inRandomOrder() method.
But this cache the result. I want ignore cache if have RAND() query.

```php
$posts = Post::inRandomOrder()->take(10)->get();
```

**Comment by Omranic** [comment]
If you want to disable cache for a specific model, that's easy by setting `protected $cacheLifetime = 0;` 
https://github.com/rinvex/laravel-cacheable#optional-features

But to disable for a specific query of a model, then you may need to override the trait to support that custom logic, as it's not supported by default.
