### ISSUE TITLE
Question: Should work on PHP 5.6 ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [rinvex/laravel-cacheable#4]
Hi, this seems to be great package !

Are you planning to support 5.6+ version of PHP. I am running LV 5.3 but wasn't able to install this on it because it enforces v7 of php.

Thanks

**Comment by Omranic** [comment]
Thank you @sarfraznawaz2005, honestly since PHP 5.6 already out of date and no longer actively maintained, we're not going to support it. But you still can fork the package, and add the following lines to your `composer.json` to use your copy of the package, but you still have to sync any update manually:
```php
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/username/repo"
        }
    ],
```

Hope you can upgrade to PHP7 soon to get benefit of all the awesome stuff 😉

**Comment by sarfraznawaz2005** [comment]
@Omranic I understand, just wanted to use this nice package in my existing projects to provide caching layer but yes for future projects I am going to use PHP7 :smile: 

I tried doing the way you mentioned and added `CacheableEloquent` in my model, also removed PHP7 `string` type hints and any return types from `CacheableEloquent` but it said:

`PHP Strict Standards: Static function 'updated' should not be abstract`

So I removed the `static` keyword from the `updated`, `created` and `deleted` functions in `CacheableEloquent` and errors were gone but query was not getting cached and no `rinvex.cacheable.json` file was generated in cache folder.

Here is the query:

    $query = Task::where('user_id', auth()->user()->id)->get();

Could it be that I removed `static` keyword ? Any ideas of how to get this working ?

Thanks

**Comment by Omranic** [comment]
Oh, let me check that now..

**Comment by sarfraznawaz2005** [comment]
@Omranic : Actually I have custom base model which extends `Ardent`: (https://github.com/laravel-ardent/ardent)

     CoreModel extends Ardent

and `Ardent` actually extends `Model`:

    Ardent extends Model

The `Model` already has those `updated`, `created` and `deleted` implementations as you know. So `CacheableEloquent` should work even if I am extending `Ardent` or some other like `Esensi` ? But it seems it is not working with any of these packages, only when I directly extend `Model`, it works. Any Ideas please ?

**Comment by sarfraznawaz2005** [comment]
Figured it out, below code in Ardent was creating the problem:

    public function newQueryWithoutScopes()
    {
        $builder = new Builder($this->newBaseQueryBuilder());
        $builder->throwOnFind = static::$throwOnFind;

        return $builder->setModel($this)->with($this->with);
    }

**Comment by sarfraznawaz2005** [comment]
Thanks again for the nice package :smile:
